export enum DatabaseErrorType {
  NOT_IN_GROUP = 'NOT_IN_GROUP',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  CLUSTER_NOT_FOUND = 'CLUSTER_NOT_FOUND',
  USERNAME_NOT_FOUND = 'USERNAME_NOT_FOUND',
  ATLAS_NETWORK_PERMISSION_ENTRY_NOT_FOUND = 'ATLAS_NETWORK_PERMISSION_ENTRY_NOT_FOUND'
}
