export enum ClientMessageType {
  REPLY_TO_CREATE_APP = 'REPLY_TO_CREATE_APP',
  REPLY_TO_DELETE_APP = 'REPLY_TO_DELETE_APP',
  REPLY_TO_CREATE_DATABASE = 'REPLY_TO_CREATE_DATABASE',
  REPLY_TO_DELETE_DATABASE = 'REPLY_TO_DELETE_DATABASE',
  REPLY_TO_CREATE_BACKEND = 'REPLY_TO_CREATE_BACKEND',
  REPLY_TO_DELETE_BACKEND = 'REPLY_TO_DELETE_BACKEND',
  REPLY_TO_GCP_CLOUD_RUN_CREATE = 'REPLY_TO_GCP_CLOUD_RUN_CREATE',
  REPLY_TO_GCP_CLOUD_RUN_DELETE = 'REPLY_TO_GCP_CLOUD_RUN_DELETE',
  REPLY_TO_DEPLOY = 'REPLY_TO_DEPLOY',
  REPLY_TECHNICAL_FAILED = 'REPLY_TECHNICAL_FAILED'
}
