export enum DatabaseMessageType {
  CREATE_DATABASE = 'CREATE_DATABASE',
  DATABASE_READY = 'DATABASE_READY',
  DATABASE_CREATION_FAILED = 'DATABASE_CREATION_FAILED',
  DELETE_DATABASE = 'DELETE_DATABASE',
  DELETE_DATABASE_SUCCEED = 'DELETE_DATABASE_SUCCEED',
  DELETE_DATABASE_FAILED = 'DELETE_DATABASE_FAILED'
}
