export enum IoMessageType {
  SCHEMA_BY_ID_REQUEST = 'SCHEMA_BY_ID_REQUEST',
  SCHEMA_BY_ID_RESPONSE = 'SCHEMA_BY_ID_RESPONSE',
  INFRA_BY_SCHEMA_ID_REQUEST = 'INFRA_BY_SCHEMA_ID_REQUEST',
  INFRA_BY_SCHEMA_ID_RESPONSE = 'INFRA_BY_SCHEMA_ID_RESPONSE',
  ACTIVITY_BY_SCHEMA_ID_REQUEST = 'ACTIVITY_BY_SCHEMA_ID_REQUEST',
  ACTIVITY_BY_SCHEMA_ID_RESPONSE = 'ACTIVITY_BY_SCHEMA_ID_RESPONSE'
}
