export enum SchemaStatusType {
  NO_INFRA = 'NO_INFRA',
  INFRA_UP = 'INFRA_UP',
  INFRA_FAILED_TO_UP = 'INFRA_FAILED_TO_UP',
  INFRA_DELETED = 'INFRA_DELETED',
  INFR_FAILED_TO_DELETE = 'INFR_FAILED_TO_DELETE',
  INFRA_UP_IN_PROCESS = 'INFRA_UP_IN_PROCESS',
  INFRA_DONW_IN_PROCESS = 'INFRA_DONW_IN_PROCESS'
}
