export enum SchematicMessageType {
  CREATE_BACKEND_API = 'CREATE_BACKEND_API',
  BACKEND_API_READY = 'BACKEND_API_READY',
  BACKEND_API_CREATION_FAILED = 'BACKEND_API_CREATION_FAILED',
  DELETE_BACKEND = 'DELETE_BACKEND',
  DELETE_BACKEND_SUCCEED = 'DELETE_BACKEND_SUCCEED',
  DELETE_BACKEND_FAILED = 'DELETE_BACKEND_FAILED'
}
