export enum SchedulerMessageType {
  CREATE_GRIIOT_APP_FAILED = 'CREATE_GRIIOT_APP_FAILED',
  CREATE_GRIIOT_APP_SUCCEED = 'CREATE_GRIIOT_APP_SUCCEED',
  DELETE_GRIIOT_APP = 'DELETE_GRIIOT_APP',
  DELETE_GRIIOT_APP_FAILED = 'DELETE_GRIIOT_APP_FAILED',
  DELETE_GRIIOT_APP_SUCCEED = 'CREATE_GRIIOT_APP_SUCCEED',
  CREATE_GRIIOT_APP = 'CREATE_GRIIOT_APP'
}
