export enum SchemaStatusType {
  NO_INFRA = 'NO_INFRA',
  INFRA_UP = 'INFRA_UP',
  INFRA_DOWN = 'INFRA_DOWN',
  INFRA_UP_IN_PROCESS = 'INFRA_UP_IN_PROCESS',
  INFRA_DONW_IN_PROCESS = 'INFRA_DONW_IN_PROCESS'
}
