export enum TechnicalMessageType {
  INFRA_TECHNICAL_FAILED = 'INFRA_TECHNICAL_FAILED',
  ONLINE_TECNICAL_FAILED = 'ONLINE_TECNICAL_FAILED',
  DATABASE_TECHNICAL_FAILED = 'DATABASE_TECHNICAL_FAILED',
  SCHEMATIC_TEHCNICAL_FAILED = 'SCHEMATIC_TEHCNICAL_FAILED',
  SCHEDULER_TECHNICAL_FAILED = 'SCHEDULER_TECHNICAL_FAILED'
}
