//TODO: this status are in order

export enum InfraStatusType {
  NEW = 'NEW',
  DATABASE_UP = 'DATABASE_UP',
  DATABASE_DOWN = 'DATABASE_DOWN',
  GITHUB_UP = 'GITHUB_UP',
  GITHUB_DOWN = 'GITHUB_DOWN',
  GCLOUD_KONG_UP = 'GCLOUD_KONG_UP',
  GCLOUD_KONG_DOWN = 'GCLOUD_KONG_DOWN',
  SECRETS_WORKFLOW_RERUN_UP = 'SECRETS_WORKFLOW_RERUN_UP',
  SECRETS_WORKFLOW_RERUN_DOWN = 'SECRETS_WORKFLOW_RERUN_DOWN',
  INFRA_UP = 'INFRA_UP',
  INFRA_DOWN = 'INFRA_DOWN',
  INFRA_PENDING = 'INFRA_PENDING'
}
